### ISSUE TITLE
Trace request traceparent id is invalid

### ISSUE THREAD

**Issue by crshanks** [newrelic-experimental/apigee-distributed-tracing#1]
## Description

The `Trace-Context-Request.js` script generates an invalid traceparent header. Instead of 8 characters (4 bytes) it should be 16 characters (8 bytes).

## Steps to Reproduce

Using the VSCode Apigee Emulator (1.6.1) and the current latest release v0.9.0. A call to `http://0.0.0.0:8998/Trace-Context` results in an error.

Note that I needed to comment out references to the 'Add-Trace-Context-To-Pub-Sub-Message' policy as steps in the proxy and target default.xml files to get the sample code in the repo to work correctly. Those policies are not present on main/latest.

## Expected Behavior

Valid W3C traceparent header generated.

## Relevant Logs / Console output

The Target trace context flow reports an invalid traceparent, as 16 characters are correctly expected:

`type= string Target-Trace-Context-Flow.TraceContextRequest: Error: invalid traceparent: 00-449ef2306648c82eeefb98ab5a9736d3-554b4619-01`

The penultimate component representing the parent is 8 characters too short.

## Your Environment

Apigee X, and VSCode Apigee Emulator 1.6.1.

## Additional context

I will submit a PR to fix shortly after creating this issue.

**Comment by msummers-nr** [comment]
Fixed via PR in release v0.9.1
